# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: 'Default'

steps: 
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    pwd
    apt-get update
    apt-get install openjdk-8-jdk
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    export USER=acme
    ./gradlew clean build bootBuildImage -x test 
    docker images
    docker login harbor.haas-451.pez.pivotal.io -u admin -p 9U0IwJXfcX
    docker tag acme/quotes-service:latest harbor.haas-451.pez.pivotal.io/dev/quotes-service:latest
    docker tag acme/user-service:latest harbor.haas-451.pez.pivotal.io/dev/user-service:latest
    docker tag acme/portfolio-service:latest harbor.haas-451.pez.pivotal.io/dev/portfolio-service:latest
    docker tag acme/accounts-service:latest harbor.haas-451.pez.pivotal.io/dev/accounts-service:latest
    docker tag acme/web-ui:latest harbor.haas-451.pez.pivotal.io/dev/web-ui:latest
    docker push harbor.haas-451.pez.pivotal.io/dev/quotes-service:latest
    docker push harbor.haas-451.pez.pivotal.io/dev/user-service:latest
    docker push harbor.haas-451.pez.pivotal.io/dev/portfolio-service:latest
    docker push harbor.haas-451.pez.pivotal.io/dev/accounts-service:latest
    docker push harbor.haas-451.pez.pivotal.io/dev/web-ui:latest
    

    
  displayName: 'Build the tanzu bank services'
