spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quote_url: https://sandbox.iexapis.com/stable/stock/{symbol}/batch?token=Tsk_64ae9801557b4deca53e380fdaee9510
    quotes_url: https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbols}&types=quote&token=Tsk_64ae9801557b4deca53e380fdaee9510
    companies_url: https://sandbox.iexapis.com/stable/stock/{name}/company?token=Tsk_64ae9801557b4deca53e380fdaee9510

